version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./settings:/app/settings
      - ./exports:/app/exports
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    restart: always